# Generated by Django 4.1.5 on 2023-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiperfurm', '0002_alter_shopregmodel_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=25)),
                ('productid', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
