# Generated by Django 4.1.5 on 2023-01-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiperfurm', '0003_uploadform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadform',
            new_name='uploadmodel',
        ),
    ]
