# Generated by Django 4.1.5 on 2023-01-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiperfurm', '0005_userregmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='image',
            field=models.ImageField(upload_to='zaiperfurm/static'),
        ),
    ]
